FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --omit=dev

COPY index.js ./

ENV NODE_ENV=production
ENV PORT=3000
ENV APP_VERSION=v1.4.0

EXPOSE 3000

USER node

CMD ["node", "index.js"]
