[kijanikiosk]
api ansible_host=10.247.111.87
payments ansible_host=10.247.111.111
logs ansible_host=10.247.111.80

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
