apiVersion: v1
kind: ConfigMap
metadata:
  name: kk-payments-config
data:
  NODE_ENV: "production"
  DB_HOST: "kijani-db-production"
  DB_PORT: "5432"
  LOG_LEVEL: "info"
  APP_PORT: "3001"
  MAX_CONNECTIONS: "100"
  RECEIPT_BUCKET: "kk-payments-receipts-production"
